name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up JDK 11 for Android
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    # Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    # Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Build the app
    - name: Build with Gradle
      run: ./gradlew build

    # Run unit tests
    - name: Run tests
      run: ./gradlew test
